/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as IndexRouteImport } from './routes/index'

const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/investor': typeof InvestorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/investor': typeof InvestorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/investor': typeof InvestorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/business' | '/investor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business' | '/investor'
  id: '__root__' | '/' | '/business' | '/investor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  InvestorRoute: typeof InvestorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  InvestorRoute: InvestorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
